### ISSUE TITLE
Remove special characters from CommCare message before loading to Salesforce

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#49]
## Describe the bug
Salesforce is responding with error `ERROR_HTTP_400: Bad Request` when we send special characters that are received from CommCare. 

Please expand the `removeAccents` function to not only remove accents, but all special characters. For example, the latest run is failing because of an "ordinal indicator" in the intervention name: `Nhamaonha 6ª Classe 2023-10-09`. 

We expect the forms to come in the following languages: Portuguese, English & Spanish (TO-DO: update list once Maluba confirms languages). **Is there a way to remove all special characters in these languages? It looks like you can find the special characters on this ASCII site: https://www.ascii-codes.com/cp860.html**

This change should be implemented on 4 jobs:
1. Register Participant 
2. Pre challenges
3. Post challenges
4. Attendance

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/grs-integrations/runs/0655dc0e-a584-7449-86dc-474f89d0d195

### expression.js
Link to the job itself in Github: 

Register participant: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/2.d.upsertRegisterParticipant.js
Pre challenges: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertPreChallenges.js
Post challenges: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertPostChallenges.js
Attendance: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertAttendanceNonSkillz.js

### state.json
Messages:

Register participant: https://www.openfn.org/projects/grs-integrations/messages/06538e92-cc44-7358-a30c-6141a52f9be4
Pre challenges: https://www.openfn.org/projects/grs-integrations/messages/06538f45-108c-7741-baeb-3a77bd993ddc
Post challenges: https://www.openfn.org/projects/grs-integrations/messages/06538f6a-5ea4-7b3c-9177-71bbf979c65a
Attendance: https://www.openfn.org/projects/grs-integrations/messages/06538ef8-b46f-7573-8237-f24c19bfd38e

```json
{
  "configuration": ["SEE LAST PASS: 'GRS Prod July 2023'"],
  "data": { "See message links above" },
}
```

## Expected behavior
The run should pass with data loaded to Salesforce

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master].
5. [Please test the change on OpenFn.org by re-running this run ([link](https://www.openfn.org/projects/grs-integrations/runs/0655dc0e-a584-7449-86dc-474f89d0d195)) and confirming success.]

**Comment by josephjclark** [comment]
Hi, a couple of inputs from me on this.

I can think of a few technical solutions:
* Continue to add explicit mappings for every expected illegal character. This will be brittle and won't scale
* We could do this mapping in the salesforce adaptor itself, which would benefit everyone, but it's still a brittle solution
* We MIGHT be able to automatically detect a character that salesforce will reject (ie, everything outside of the standard unicode set, and map or remove it. This would happen in the salesforce adaptor.

The problem here, apart from scaling, is that replacing or removing these characters could change the meaning of the data. It's a bit risky to automatically change the data!

It MIGHT be more appropriate to reject the entries with invalid characters (with we let Salesforce do it or we intervene in the salesforce adaptor), and have a human come in and correct the data in commcare directly. That's obviously going to be a different workflow but it might be the best way forward.

**Comment by stuartc** [comment]
Does anyone know what character set is supported by Salesforce? Like what standard or sub-set of a standard?

**Comment by daissatou2** [comment]
@mtuchi these are message filter jobs not flow jobs so we'll need to add the fix to all of them.

**Comment by mtuchi** [comment]
@daissatou2 i have cut a new version of salesforce `v4.3.0` and used the new function called `toUTF8` as a replacement of `replaceAccents` function. You can proceed with testing on platform but make sure the salesforce adaptor version is `v4.3.0`

cc @aleksa-krolls

**Comment by daissatou2** [comment]
@mtuchi this looks good. Ready for code review.

**Comment by mtuchi** [comment]
@daissatou2 can we close this issue ?, Joe already approve the changes to the salesforce adaptor on https://github.com/OpenFn/adaptors/pull/441. And i doin't think he has access to this repo

**Comment by mtuchi** [comment]
@daissatou2 Joe approved the changes in https://github.com/OpenFn/adaptors/pull/441.
I don't have access to close this issue, If you have access to closing issue, please close it.
